encrypt: encrypt.cpp encrypt.hpp string_utils.cpp string_utils.hpp
	g++ -o encrypt -std=c++11 encrypt.cpp

decrypt: decrypt.cpp encrypt.hpp string_utils.cpp string_utils.hpp
	g++ -o decrypt -std=c++11 decrypt.cpp
